org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
org.gradle.configuration-cache=false

mod.id=shwgconfig
mod.name=Shwg Configs
mod.version=0.1.0-alpha.1
mod.group=dev.shwg
mod.description=Fabric, Forge & NeoForge client config library.

#custom
mod.issueUrl=https://github.com
mod.license=MIT
mod.authors=Schauweg

#releasing
MODRINTH_ID=shwgconfig
