#minecraft
minecraft_version=26.3
#additional_versions=

#fabric
loader_version=0.19.5
fabric_version=0.160.5+26.3
modmenu_version=21.0.0-beta.1

#neoforge
neoforge_version=26.3.0.0-beta

#forge
forge_version=26.3-66.0.2
forge_loader_version=66.0.2
